name: Build
on:
  push:
    branches: [main, master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Clean Flutter Build Cache
      run: flutter clean

    
    - name: Install Dependencies
      run: flutter pub get

    - name: Repair Missing Android Files
      run: flutter create . --platforms=android

    # Pastikan Package Name sesuai dengan folder java kita tadi
    - name: Set Android Bundle ID
      run: |
        dart run rename setBundleId \
        --value "com.heruwingchun.hpki" \
        --targets android

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Zona-Beladiri-APK
        path: build/app/outputs/flutter-apk/app-release.apk